import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navber";
import NextAuthSessionProvider from "@/Providers/NextAuthSessonProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Next.js App",
  },
  
  keyword: "nextjs, app, example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
      <body
        className={` ${poppins.className} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">
           {children}
        </main>
       
        <footer className="text-center p-4 bg-gray-50 dark:bg-gray-800">
          <p>© 2023 My Next.js App</p>
        </footer>
      </div>
      </body>
      </NextAuthSessionProvider>
    </html>
  );
}
